# Generated by Django 2.1.7 on 2019-02-25 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fein', models.CharField(max_length=9)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractor.Person')),
            ],
        ),
    ]
