# Generated by Django 2.1.7 on 2019-02-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0002_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='address',
            field=models.CharField(default='glenview, il', max_length=150),
            preserve_default=False,
        ),
    ]
